### ISSUE TITLE
NcnnDotNet.Native  can't use on arm cpu

### ISSUE THREAD

**Issue by chatop2020** [takuya-takeuchi/NcnnDotNet#23]
can you support arm cpu?

**Comment by takuya-takeuchi** [comment]
@chatop2020 
https://github.com/takuya-takeuchi/NcnnDotNet/tree/develop
We have already supported android but it is not published yet.
And I have no android device and arm device. So I cannot test it.

Thanks.

**Comment by chatop2020** [comment]
i want use on raspberrypi 4b ,it powered by arm cpu,running linux (debian 64bit) os
thanks ,i will try it

**Comment by chatop2020** [comment]
i have test this devel version,it can't build for raspberry 4b by debian 64bit (arm64) also.

**Comment by takuya-takeuchi** [comment]
@chatop2020 
I remembered that I have chromebook and I tested lib.
It works fine except for gui functions.

This PR have already merged to develop.
https://github.com/takuya-takeuchi/NcnnDotNet/pull/24

You can execute this script on x86_64 linux machine rather than arm machine.

1. BuildDevel.ps1 in docker directory
1. run BuildUbuntu16.ps1 in nuget directory

It could generate libNcnnDotNetNative.so.

**Comment by chatop2020** [comment]
Thank you. I have found the NCNNSHARP project, which has been successfully tested and can run smoothly on the Raspberrypi device

**Comment by takuya-takeuchi** [comment]
I'm glad to hear that you achieve your purpose.

**Comment by chatop2020** [comment]
Thanks, I tried NCNNSHARP's  C_API with Ncnn, it very easy to use, it is recommended that you can use C_API Also.
