### ISSUE TITLE
Native binary is not deployed for .NET Frameworks

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/NcnnDotNet#8]

**Comment by takuya-takeuchi** [comment]
Maybe, **NcnnDotNet\nuget\nuspec\build\NcnnDotNet.targets** is not inclued in nuspec. It could be why this issue occurs.

**Comment by GabrielBottari** [comment]
Hello,

We are having potentially related issue where we get the error : 

Unable to load DLL 'NcnnDotNetNative' or one of its dependencies: The specified module could not be found. (0x8007007E)

This happens when installing our application to program files, even though the both binaries are clearly there in the same folder. This does not happen on our development machines either.

Any pointers or possible workaround?
